apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nginx:1.25

        resources:
          limits:
            cpu: "400m"
            memory: "200Mi"
          requests:
            cpu: "200m"
            memory: "100Mi"

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5